# -*- mode: ruby -*-
# vi: set ft=ruby :

require "fileutils"

FORGEJO_DOMAIN = ENV["FORGEJO_DOMAIN"] || raise("FORGEJO_DOMAIN env var is required. Example: FORGEJO_DOMAIN=forgejo.example.com vagrant up")

Vagrant.configure("2") do |config|
  # Forgejo: 2 vCPU, 2 GB RAM, 50 GB disk, private IP 192.168.56.10
  config.vm.define "forgejo" do |vm|
    vm.vm.box = "cloud-image/debian-13"
    vm.vm.hostname = "forgejo"
    vm.vm.synced_folder ".", "/vagrant", disabled: true
    vm.vm.network "private_network", ip: "192.168.56.10"
    # Forgejo HTTPS web UI
    vm.vm.network "forwarded_port", guest: 3000, host: 3000
    # Forgejo git SSH
    vm.vm.network "forwarded_port", guest: 2222, host: 2222
    vm.vm.disk :disk, size: "50GB", primary: true
    vm.vm.provider "virtualbox" do |vb|
      vb.name = "forgejo"
      vb.memory = 2048
      vb.cpus = 2
    end
    vm.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io docker-compose
      systemctl enable docker
      systemctl start docker
      usermod -aG docker vagrant
    SHELL

    vm.trigger.after :up do |trigger|
      trigger.ruby do |env, machine|
        ssh = machine.ssh_info
        inventory_path = File.expand_path("../../ansible/inventory/dev/vagrant-vb/inventory.ini", __dir__)
        FileUtils.mkdir_p(File.dirname(inventory_path))
        File.write(inventory_path, <<~INI)
          [all]
          forgejo ansible_host=#{ssh[:host]} ansible_port=#{ssh[:port]} ansible_ssh_private_key_file=#{ssh[:private_key_path].first}

          [containers]
          forgejo

          [forgejo]
          forgejo

          [all:vars]
          ansible_user=vagrant
          ansible_python_interpreter=/usr/bin/python3.13
          forgejo_domain=#{FORGEJO_DOMAIN}
        INI
        puts "Inventory written to: #{inventory_path}"
      end
    end
  end
end
